# -*- coding: utf-8 -*-
"""Analise de vendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaVw0ywiv8yFaxi7yS1n7kSgVneSOSYQ
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("rohitsahoo/sales-forecasting")

print("Path to dataset files:", path)

import pandas as pd
import matplotlib.pyplot as plt

# carregar dados
df = pd.read_csv(path + '/train.csv')

# ver dados
print(df.head())

# info geral
print(df.info())

# verificar nulos
print(df.isnull().sum())

df = df.drop_duplicates()

# converter data (se tiver coluna de data)
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

# garantir valores corretos
df['Sales'] = df['Sales'].astype(float)

total_sales = df['Sales'].sum()
print(f"Total Revenue:{total_sales:.2f}")

top_products = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False)
print(top_products.head())

df['Month'] = df['Order Date'].dt.month

monthly_sales = df.groupby('Month')['Sales'].sum()

monthly_sales.plot(kind='line')
plt.title("Sales by Month")
plt.show()

top_selling_product_per_region = df.groupby(['Region', 'Product Name'])['Sales'].sum()
max_sales_per_region = top_selling_product_per_region.groupby('Region').idxmax()

print("Best-selling product by region:")
for region, product_info in max_sales_per_region.items():
    product_name = product_info[1] # Product Name is the second element in the tuple
    sales = top_selling_product_per_region.loc[region, product_name]
    print(f"Region: {region}, Product: {product_name}, Sales: {sales:.2f}$")

top_products.head(5).plot(kind='bar')
plt.title("Top Products")
plt.show()

"""The Canon imageCLASS 2200 Advanced Copier was the primary revenue driver, dominating sales across nearly all regions.
The South region presented a distinct pattern, with the Cisco TelePresence System EX90 outperforming other products, suggesting regional demand differences.
Sales analysis revealed clear seasonality, with peaks in September and November, which may be linked to promotional periods or increased market demand.
The business achieved a total annual revenue of €2.26M, indicating a solid commercial performance.

"""